name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js / Access to 'npm' command
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm

      - name: Install JSDocs
        run: npm i -g jsdocs
        
      - name: Install Docdash template
        run: npm i docdash

      - name: Run "docs" script to update documentation
        run: npm run docs

      - name: Push Docs to Master
        uses: ad-m/github-push-action@master