name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install JSDocs
        uses: npm i -g jsdocs
        
      - name: Install Docdash template
        uses: npm i docdash

      - name: Run "docs" script to update documentation
        uses: npm run docs

      - name: Push Docs to Master
        uses: ad-m/github-push-action@master
