name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js / Access to 'npm' command
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm

      - name: Install JSDocs and Docdash template
        run: npm install
      - run: npm run build

      - name: Run "docs" script to update documentation
        run: npm run docs

      - name: upload artifacts ("package or set of files, resulting from a build process")
        uses: actions/upload-pages-artifact@v1
        with: 
          path: "./docs"
